[package]
name = "wocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
httparse = "1.8.0"
sha1 = "0.10.6"
tokio = { version = "1.36.0", features = ["full"] }
